### ISSUE TITLE
Easy filtering of data based on dynamic field values - campus and school for students

### ISSUE THREAD

**Issue by abhilashnavgurukul** [navgurukul/ghar#80] opened 2024-01-05 11:37 UTC
When filtering students based on school, all the available schools should be listed for selection. As of now nothing is displayed and user have to manually type the school name. A mistake in spelling will show empty result. 

Currently for filtering by status, all the available status values are listed for selection. Similarly functionality we require for campus, schools, and any other fields where we have specific set of values for the field. This is true for all the forms.

Checkout the video -

https://github.com/navgurukul/ghar/assets/117743777/7785df1b-b885-4a9c-a340-9e2ba4f68d23

**Comment by Vijay-train** [comment] 2024-01-09 07:39
This is by design. Only Drop down fields show the values in search We have created filter for campus ( to filter specific campus), we can add it for school as well., if need be. However, i dont think this is a high priority at this point. Hence resolving

**Closed by Vijay-train** 2024-01-09 07:39 UTC
Labels: bug, enhancement
